# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.library_handler:
        class:     AppBundle\Service\LibraryHandler
        arguments: [ "@doctrine.orm.entity_manager" ]
